#!/bin/sh

mute="$(pamixer --get-mute)"
vol="$(pamixer --get-volume | awk '{print $1}')"
if [ $mute = true ]; then
    i='ﱝ'
    vol="0"
elif [ $mute = false ]; then
    case ${vol%?} in
           10) i='' ;;
        [6-9]) i='墳' ;;
        [3-5]) i='奔' ;;
            *) i=''
    esac
fi

printf "%s%%\n" "$i $vol"
